FROM python:3.8-slim

RUN apt-get update && apt-get install -y libgomp1 libgl1-mesa-glx libglib2.0-0 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY run_mores.py .
COPY run.sh .
COPY train_det_full.py .
COPY checkpoints/det_model_epoch20.pdparams /app/model.pdparams

RUN pip install --no-cache-dir paddlepaddle==2.6.2 opencv-python-headless numpy

RUN chmod +x /app/run.sh

CMD ["/app/run.sh"]